title: Service Providers
url: https://oai-demandgen.github.io/service-providers/

github_user: oai-demandgen
github_repo: service-providers
github_branch: master

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
