title: People
url: https://api-specification-toolbox.io/people/

github_user: oai-demandgen
github_repo: people
github_branch: master

version:      1.1.2
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
